version: '3'

services:
  app:
    build: 
      dockerfile: dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8081:8081
      - 5001:5001

  mailhog:
    image: 'mailhog/mailhog:latest'
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
